### ISSUE TITLE
Testing the binary package of hokuyo3d.

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/icart#110]
@Nasupl hokuyo3dのバイナリパッケージがパブリックリリースされています。

``` sh
$ sudo apt-get install ros-indigo-hokuyo3d
```

で導入可能になったため、ローカルでビルドしたものを完全に削除してからパッケージ版で実機の動作確認をお願いします。

**Comment by DaikiMaekawa** [comment]
あれ、でも返却するとすれば現行のソースも意味を成さなくなるということか。 来年度に向けた機体はどのような構成にする予定でしょうか?

**Comment by yasuohayashibara** [comment]
こちらすでにhokuyo3dを使用していないためissueを閉じます．
