### ISSUE TITLE
シミュレータで自律走行すると軌道にうまく追従しない(melodic)

### ISSUE THREAD

**Issue by hoshianaaa** [open-rdc/icart#125]
#124

**Comment by yasuohayashibara** [comment]
現在は追従できている．

もしかしたら質量が大きかったことが問題だったかもしれません．
https://github.com/open-rdc/orne_navigation/pull/508#discussion_r551715092

**Comment by yasuohayashibara** [comment]
解決したのでissueを閉じます．
