### ISSUE TITLE
catkin_makeでエラー

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/icart#66]
mirai@ubuntu:~/CATKIN_WORKSPACE$ catkin_make
Base path: /home/mirai/CATKIN_WORKSPACE
Source space: /home/mirai/CATKIN_WORKSPACE/src
Build space: /home/mirai/CATKIN_WORKSPACE/build
Devel space: /home/mirai/CATKIN_WORKSPACE/devel
Install space: /home/mirai/CATKIN_WORKSPACE/install
#### 
#### 

-- Using CATKIN_DEVEL_PREFIX: /home/mirai/CATKIN_WORKSPACE/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/mirai/CATKIN_WORKSPACE/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.11
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 22 packages in topological order:
-- ~~  - icart_mini (metapackage)
-- ~~  - icart_mini_description
-- ~~  - icart_mini_navigation
-- ~~  - ros_controllers (metapackage)
-- ~~  - rqt_joint_trajectory_controller
-- ~~  - forward_command_controller
-- ~~  - position_controllers
-- ~~  - waypoints_navigation
-- ~~  - force_torque_sensor_controller
-- ~~  - icart_mini_driver
-- ~~  - imu_sensor_controller
-- ~~  - joint_state_controller
-- ~~  - combine_dr_measurements
-- ~~  - force_rotate_recovery
-- ~~  - imu
-- ~~  - effort_controllers
-- ~~  - icart_mini_gazebo
-- ~~  - velocity_controllers
-- ~~  - diff_drive_controller
-- ~~  - gripper_action_controller
-- ~~  - icart_mini_control
-- ~~  - joint_trajectory_controller
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'icart_mini'
-- ==> add_subdirectory(icart_mini/icart_mini)
-- +++ processing catkin package: 'icart_mini_description'
-- ==> add_subdirectory(icart_mini/icart_mini_description)
-- +++ processing catkin package: 'icart_mini_navigation'
-- ==> add_subdirectory(icart_mini/icart_mini_navigation)
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "move_base_msgs"
  with any of the following names:

```
move_base_msgsConfig.cmake
move_base_msgs-config.cmake
```

  Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set
  "move_base_msgs_DIR" to a directory containing one of the above files.  If
  "move_base_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  icart_mini/icart_mini_navigation/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mirai/CATKIN_WORKSPACE/build/CMakeFiles/CMakeOutput.log".
See also "/home/mirai/CATKIN_WORKSPACE/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by DaikiMaekawa** [comment]
`rosdep install`を実行済みであれば、依存パッケージの設定漏れということになりますね。(後で修正しておきます)

``` sh
$ sudo aptitude install ros-indigo-move-base-msgs
```

を実行してみてください。

**Comment by yasuohayashibara** [comment]
インストールの手順の中でrosdep updateを実行していませんでした．

**Comment by DaikiMaekawa** [comment]
なるほど、`rosdep install`時にエラーが表示され`rosdep update`の実行を促される場合があるので、それに従うようにしましょう。
